title: 青椒之梯
description: 高校青年教师纵向科研项目资源库
theme: just-the-docs
url: "https://你的GitHub用户名.github.io"
baseurl: "/Qingjiao"

search_enabled: true
search.tokenizer_separator: /[\s/]+/

nav_order: 1
aux_links:
  "GitHub 仓库":
    - "https://github.com/xingyezn/Qingjiao"

lang: zh-CN
